[package]
name = "blockchain"
version = "0.1.0"
authors = ["Andrew <arellok@gmail.com>"]

[dependencies]
env_logger = "0.5.3"
futures = "*"
hyper = "*"
log = "0.4.1"
serde = "*"
serde_derive = "*"
serde_json = "*"
syn = "0.12.7"
url = "1.6.0"
